version: '3.7'

x-labels:
  labels: &default-label
    oracle:

services:
  ## https://container-registry.oracle.com/ords/ocr/ba/database/free
  oracle:
    image: container-registry.oracle.com/database/free:23.3.0.0
    labels: *default-label
    restart: always
    ports: 
      - "1521:1521"
    volumes:
      - oracle:/opt/oracle/oradata
    env_file:
      - .env
    environment:
      - TZ=Asia/Taipei
      - ORACLE_PWD=${SYS_PWD}
      - ORACLE_CHARACTERSET=AL32UTF8

  backup:
    build: ./volume-backup
    restart: "no"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - oracle:/volume:ro
      - backup:/backup
    environment:
      - BACKUP_LABEL=oracle
    command: ./backup.sh
    network_mode: none

  # restore:
  #   build: ./volume-backup
  #   restart: "no"
  #   env_file:
  #     - .env
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - oracle:/volume 
  #     - backup:/backup:ro
  #   environment:
  #     - BACKUP_LABEL=oracle
  #   command: ./restore.sh
  #   network_mode: none

volumes:
  oracle:
    labels: *default-label
    ## If you encounter different volume names during backup/restore, please declare the name here.
    # name: docker-oracle-database_oracle
  backup:
    driver_opts:
      type: cifs
      o: ${CIFS_OPTION}
      device: ${BACKUP_FOLDER}
